### ISSUE TITLE
unclear about driver / firmware *precise* versions

### ISSUE THREAD

**Issue by andy-shev** [jfwells/linux-asus-t100ta#2]
There are few questions:
- What **precise** versions of the driver and firmware (URLs, please!)?
- What the status of running this against vanilla kernel where AtomISPv2 (a version of) is pushed?

**Comment by ghost** [comment]
Hello,

This project is old and may possibly be dead. However, I have been working on building a portage overlay for this device for Gentoo.

This may help you,

https://github.com/lramage94/linux-asus-t100ta/wiki/Hardware

**Comment by andy-shev** [comment]
@lramage94
Good luck! (sarcasm implied)
This repository is not enough to have. The AtomISP v2 requires a *very precise* version if firmware. This repository lacks of the firmware blob, thus almost useless.

**Comment by ghost** [comment]
Oh really? The one from the Magic Stick works well.

**Comment by andy-shev** [comment]
@lramage94
And where is firmware?

**Comment by ghost** [comment]
Just boot into magic stick and extract it manually.

**Comment by ghost** [comment]
Check these out,

- https://github.com/TheDrHax/t100ta-kernel

- https://github.com/TheDrHax/t100ta-scripts

**Comment by andy-shev** [comment]
@lramage94 , yeah, yeah. Second repository has nothing to do with camera (or I missed it? Show the __exact__ filename and path in it to look at, please). The first one is too big to find a firmware. Care to providfe a link?
P.S. Throwing links to some repositories, without __exact__ points, to this bug is not helpful anyhow.

**Comment by rmast** [comment]
As far as I can find based on the date and the 4.4 version mentioned for the camera patch we must be looking at the initial 4.4 version. You can browse that version in git here:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/drivers/media/v4l2-core/videobuf2-dma-contig.c?h=linux-4.4.y

Lots of camera files are "new" in the patch, that's why it's called 'rebased' to 4.4.

Next step is to find the right Linux taste to compile it for. Fedora 18, as written in the Readme is clearly way to old for kernel 4.4, so I'll try a 4.4 linux instead, which will probably also have less issues with UEFI32.

**Comment by andy-shev** [comment]
There is no more upstreamed driver, so, nothing to worry about anymore.
https://bugzilla.kernel.org/show_bug.cgi?id=109821

**Comment by rmast** [comment]
I wonder whether this patch really needs "AtomISP v2", as all references to atomisp2 are just made in or pointing to the new contained files. So it would be possible to put effort in it to get this patch working on 4.4, with all it's TODO's and known bugs. However even I don't have the exact t100ta at my disposal. My father has a t200tac, and that has different camera's both on front and on rear. I'm just annoyed by the camera light staying on, it's shining in my eyes. And I like the nerdy approach, not the sticker.

**Comment by rmast** [comment]
I guess the best approach would be to take https://github.com/TheDrHax/t100ta-kernel as a base. 
As far as I could see between 4.4 and 4.15 many files stayed the same, so 4.7 or 4.8 would probably be a good start. I'll just get some different versions and start patching, look where it gets stuck.

**Comment by rmast** [comment]
Patching on 4.4 gave no error whatsoever.

Download https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/snapshot/linux-4.4.y.tar.gz
untar it, step into linux-4.4.y and run
patch -p1 -i ../Downloads/intel-atomisp2-mrfld.jfw.patch

**Comment by rmast** [comment]
https://github.com/TheDrHax/t100ta-kernel
contains a 4.4, 4.7 and 4.8 branch, defaulting to 4.7. However there are so many forks that it's not possible to browse for any other initiatives concerning the camera's.

Next step would be to assess the quality of one of these 3 branches. If there is a Magic stick out there with some good reviews we can look up the corresponding kernel version and try to build a Magic stick with buggy camera support...

**Comment by rmast** [comment]
Magic Stick with 4.8 kernel is recommended to work on as far as I can see...
